// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRzHmHzENX_y7DnzjUhRQLBkxQ89rboBc',
    appId: '1:810942647530:web:216cfed06445e7d0839b93',
    messagingSenderId: '810942647530',
    projectId: 'manage-skating-help',
    authDomain: 'manage-skating-help.firebaseapp.com',
    storageBucket: 'manage-skating-help.firebasestorage.app',
    measurementId: 'G-7MT8SW37YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH0_6tzxsX_rGBd3IWR7t4XzS0k5_Qbl4',
    appId: '1:810942647530:android:6e33f2dd25ab92f3839b93',
    messagingSenderId: '810942647530',
    projectId: 'manage-skating-help',
    storageBucket: 'manage-skating-help.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqTen_9itZUZTNDGdaxjzT8JuJ-6OU7GU',
    appId: '1:810942647530:ios:1e0c8b592056e987839b93',
    messagingSenderId: '810942647530',
    projectId: 'manage-skating-help',
    storageBucket: 'manage-skating-help.firebasestorage.app',
    iosBundleId: 'com.example.stressManagementByZoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqTen_9itZUZTNDGdaxjzT8JuJ-6OU7GU',
    appId: '1:810942647530:ios:1e0c8b592056e987839b93',
    messagingSenderId: '810942647530',
    projectId: 'manage-skating-help',
    storageBucket: 'manage-skating-help.firebasestorage.app',
    iosBundleId: 'com.example.stressManagementByZoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRzHmHzENX_y7DnzjUhRQLBkxQ89rboBc',
    appId: '1:810942647530:web:2cff2d421fa4c088839b93',
    messagingSenderId: '810942647530',
    projectId: 'manage-skating-help',
    authDomain: 'manage-skating-help.firebaseapp.com',
    storageBucket: 'manage-skating-help.firebasestorage.app',
    measurementId: 'G-890BLXT7L2',
  );

}